/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lukedew99 (https://sketchfab.com/lukedew99)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tshirt-493ccd4e2b6a443c87ba4264fe7cadfa
Title: Tshirt
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tshirt(props) {
  const { nodes, materials } = useGLTF('./models/tshirt.glb')
  return (
    <group {...props} dispose={null}
    scale={0.009}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh

          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Shirt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Shirt}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/tshirt.glb')
