/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations, Sparkles } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Animation3.glb')
  const { actions } = useAnimations(animations, group)

  // Création d'un matériau blanc simple
  const whiteMaterial = new THREE.MeshStandardMaterial({
    color: '#ffffff',
    roughness: 0.3,
    metalness: 0.1,
  })

  const handleClick = () => {
    // Réinitialise et joue l'animation
    Object.values(actions).forEach(action => {
      action.reset().play()
    })
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          onClick={handleClick}
          onPointerEnter={(e) => document.body.style.cursor = 'pointer'}
          onPointerLeave={(e) => document.body.style.cursor = 'default'}
          name="Sphere"
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials['Material.003']}
          position={[-0.455, 2.372, 17.224]}
          rotation={[1.482, 0.815, 0.095]}
          scale={2.535}
        />
        <group name="pin" position={[0, 0, -2.425]}>
          <mesh
            name="Circle"
            castShadow
            receiveShadow
            geometry={nodes.Circle.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Circle_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle_1.geometry}
            material={materials['Material.005']}
          />
          <mesh
            name="Sphere001"
            castShadow
            receiveShadow
            geometry={nodes.Sphere001.geometry}
            material={materials.Eye}
            position={[0.359, 6.898, 0.122]}
            scale={0.237}>
            <mesh
              name="Sphere004"
              castShadow
              receiveShadow
              geometry={nodes.Sphere004.geometry}
              material={materials.pupil}
              position={[0.637, 0, 0.098]}
              scale={0.62}
            />
          </mesh>
          <mesh
            name="Sphere002"
            castShadow
            receiveShadow
            geometry={nodes.Sphere002.geometry}
            material={materials.Eye}
            position={[0.359, 6.898, -0.464]}
            scale={0.237}>
            <mesh
              name="Sphere003"
              castShadow
              receiveShadow
              geometry={nodes.Sphere003.geometry}
              material={materials.pupil}
              position={[0.637, 0, 0]}
              scale={0.62}
            />
          </mesh>
        </group>
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={whiteMaterial}
          scale={35.087}
        />
        <group name="pin001" position={[-1.264, 0, -4.956]}>
          <mesh
            name="Circle002"
            castShadow
            receiveShadow
            geometry={nodes.Circle002.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Circle002_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle002_1.geometry}
            material={materials['Material.005']}
          />
          <mesh
            name="Sphere005"
            castShadow
            receiveShadow
            geometry={nodes.Sphere005.geometry}
            material={materials.Eye}
            position={[0.359, 6.898, 0.122]}
            scale={0.237}>
            <mesh
              name="Sphere008"
              castShadow
              receiveShadow
              geometry={nodes.Sphere008.geometry}
              material={materials.pupil}
              position={[0.637, 0, 0.098]}
              scale={0.62}
            />
          </mesh>
          <mesh
            name="Sphere006"
            castShadow
            receiveShadow
            geometry={nodes.Sphere006.geometry}
            material={materials.Eye}
            position={[0.359, 6.898, -0.464]}
            scale={0.237}>
            <mesh
              name="Sphere007"
              castShadow
              receiveShadow
              geometry={nodes.Sphere007.geometry}
              material={materials.pupil}
              position={[0.637, 0, 0]}
              scale={0.62}
            />
          </mesh>
        </group>
        <group name="pin002" position={[-1.264, 0, 0.465]}>
          <mesh
            name="Circle003"
            castShadow
            receiveShadow
            geometry={nodes.Circle003.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Circle003_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle003_1.geometry}
            material={materials['Material.005']}
          />
          <mesh
            name="Sphere009"
            castShadow
            receiveShadow
            geometry={nodes.Sphere009.geometry}
            material={materials.Eye}
            position={[0.359, 6.898, 0.122]}
            scale={0.237}>
            <mesh
              name="Sphere012"
              castShadow
              receiveShadow
              geometry={nodes.Sphere012.geometry}
              material={materials.pupil}
              position={[0.637, 0, 0.098]}
              scale={0.62}
            />
          </mesh>
          <mesh
            name="Sphere010"
            castShadow
            receiveShadow
            geometry={nodes.Sphere010.geometry}
            material={materials.Eye}
            position={[0.359, 6.898, -0.464]}
            scale={0.237}>
            <mesh
              name="Sphere011"
              castShadow
              receiveShadow
              geometry={nodes.Sphere011.geometry}
              material={materials.pupil}
              position={[0.637, 0, 0]}
              scale={0.62}
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Animation3.glb')
